//
// Created by Андрей Москалёв on 29.09.2021.
//

#ifndef HOMEWORK_1_HOMEWORK_TASK_1_CODE_CONSTANTS_H_
#define HOMEWORK_1_HOMEWORK_TASK_1_CODE_CONSTANTS_H_

const size_t MAX_NAME_LEN = 20;
const size_t MIN_YEAR = 1940;

#endif //HOMEWORK_1_HOMEWORK_TASK_1_CODE_CONSTANTS_H_
