#ifndef HOMEWORK_2_HOMEWORK_TASK_1_CODE_CONSTANTS_H_
#define HOMEWORK_2_HOMEWORK_TASK_1_CODE_CONSTANTS_H_

const size_t MAX_NAME_LEN = 20;
const size_t MIN_YEAR = 1940;

#endif //HOMEWORK_1_HOMEWORK_TASK_1_CODE_CONSTANTS_H_